[mongodb]
mongodb.bharath2103.online
[catalogue]
catalogue.bharath2103.online
[redis]
redis.bharath2103.online
[user]
user.bharath2103.online
[cart]
cart.bharath2103.online
[frontend]
bharath2103.online
[mysql]
mysql.bharath2103.online
; [shipping]
; shipping.bharath2103.online
; [rabbitmq]
; rabbitmq.bharath2103.online
; [payment]
; payment.bharath2103.online